2023-05-24 22:16:51,438 INFO root MainThread : Started
2023-05-24 22:16:51,454 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:19:45,094 INFO root waitress-0 : /validateImage....
2023-05-24 22:19:45,096 INFO root waitress-0 : >>----->>> START:UUID:=fca025b9-fa52-11ed-867b-161333e62825 <<<-----<<
2023-05-24 22:19:45,097 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:19:45,353 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:19:45,354 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:19:45,604 DEBUG root waitress-0 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:19:45,606 DEBUG root waitress-0 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:19:45,868 DEBUG root waitress-0 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:19:45,870 ERROR app waitress-0 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 70, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:20:27,143 INFO root MainThread : Started
2023-05-24 22:20:27,161 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:20:34,800 INFO root waitress-0 : /validateImage....
2023-05-24 22:20:34,801 INFO root waitress-0 : >>----->>> START:UUID:=1a4086fe-fa53-11ed-ba40-161333e62825 <<<-----<<
2023-05-24 22:20:34,803 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:20:35,061 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:20:35,062 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:20:35,293 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:20:35,485 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:20:35,786 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:20:36,096 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:20:36,154 INFO root waitress-0 : Actual sign Dim=height=153 width=96
2023-05-24 22:20:36,155 INFO root waitress-0 : Required sign Dim=height=400 width=1000
2023-05-24 22:20:36,156 INFO root waitress-0 : _isblur1_=false isvalidface=true
2023-05-24 22:20:36,157 INFO root waitress-0 : >>----->>> END:UUID:=1a4086fe-fa53-11ed-ba40-161333e62825 <<<-----<<
2023-05-24 22:20:46,329 INFO root waitress-1 : /validateImage....
2023-05-24 22:20:46,331 INFO root waitress-1 : >>----->>> START:UUID:=211fd8d6-fa53-11ed-aa75-161333e62825 <<<-----<<
2023-05-24 22:20:46,332 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:20:46,525 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:20:46,526 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:20:46,762 DEBUG root waitress-1 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:20:46,764 DEBUG root waitress-1 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:20:47,016 DEBUG root waitress-1 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:20:47,018 ERROR app waitress-1 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 70, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:21:53,072 INFO root MainThread : Started
2023-05-24 22:21:53,089 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:21:54,339 INFO root waitress-0 : /validateImage....
2023-05-24 22:21:54,342 INFO root waitress-0 : >>----->>> START:UUID:=49a95324-fa53-11ed-91e9-161333e62825 <<<-----<<
2023-05-24 22:21:54,343 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:22:15,746 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:22:15,748 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:22:16,049 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:22:16,260 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:22:16,577 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:22:16,783 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:22:17,285 INFO root waitress-0 : Actual sign Dim=height=153 width=96
2023-05-24 22:22:17,286 INFO root waitress-0 : Required sign Dim=height=400 width=1000
2023-05-24 22:22:17,287 INFO root waitress-0 : _isblur1_=false isvalidface=true
2023-05-24 22:22:17,288 INFO root waitress-0 : >>----->>> END:UUID:=49a95324-fa53-11ed-91e9-161333e62825 <<<-----<<
2023-05-24 22:22:33,778 INFO root waitress-1 : /validateImage....
2023-05-24 22:22:33,779 INFO root waitress-1 : >>----->>> START:UUID:=612aff58-fa53-11ed-9f7c-161333e62825 <<<-----<<
2023-05-24 22:22:33,781 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:22:34,010 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:22:34,012 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:22:34,254 DEBUG root waitress-1 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:22:34,255 DEBUG root waitress-1 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:22:34,497 DEBUG root waitress-1 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:22:34,498 ERROR app waitress-1 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 71, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:24:56,315 INFO root MainThread : Started
2023-05-24 22:24:56,332 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:24:57,763 INFO root waitress-0 : /validateImage....
2023-05-24 22:24:57,764 INFO root waitress-0 : >>----->>> START:UUID:=b6fd76e5-fa53-11ed-b344-161333e62825 <<<-----<<
2023-05-24 22:24:57,767 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:24:58,004 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:24:58,006 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:24:58,355 DEBUG root waitress-0 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:24:58,357 DEBUG root waitress-0 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:24:58,593 DEBUG root waitress-0 : Exception@get_image=The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-05-24 22:24:58,595 ERROR app waitress-0 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 72, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:26:28,042 INFO root MainThread : Started
2023-05-24 22:26:28,059 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:26:29,661 INFO root waitress-0 : /validateImage....
2023-05-24 22:26:29,662 INFO root waitress-0 : >>----->>> START:UUID:=edc3fed1-fa53-11ed-973a-161333e62825 <<<-----<<
2023-05-24 22:26:29,665 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:26:29,905 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:26:29,907 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:26:30,438 INFO root waitress-0 : Actual sign Dim=height=80 width=344
2023-05-24 22:26:30,439 INFO root waitress-0 : Required sign Dim=height=400 width=1000
2023-05-24 22:26:30,441 INFO root waitress-0 : _isblur1_=false isvalidface=true
2023-05-24 22:26:30,441 INFO root waitress-0 : >>----->>> END:UUID:=edc3fed1-fa53-11ed-973a-161333e62825 <<<-----<<
2023-05-24 22:26:35,446 INFO root waitress-1 : /validateImage....
2023-05-24 22:26:35,447 INFO root waitress-1 : >>----->>> START:UUID:=f136b20f-fa53-11ed-8aaf-161333e62825 <<<-----<<
2023-05-24 22:26:35,448 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:26:35,690 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:26:35,691 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:26:35,909 DEBUG root waitress-1 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:26:36,155 ERROR app waitress-1 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 72, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:27:23,883 INFO root MainThread : Started
2023-05-24 22:27:23,901 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:27:25,394 INFO root waitress-0 : /validateImage....
2023-05-24 22:27:25,395 INFO root waitress-0 : >>----->>> START:UUID:=0efc1320-fa54-11ed-b2b5-161333e62825 <<<-----<<
2023-05-24 22:27:25,397 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:27:25,619 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:27:25,620 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:27:25,849 DEBUG root waitress-0 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:27:26,080 ERROR app waitress-0 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 73, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:27:38,374 INFO root waitress-1 : /validateImage....
2023-05-24 22:27:38,375 INFO root waitress-1 : >>----->>> START:UUID:=16b8bd7d-fa54-11ed-aabc-161333e62825 <<<-----<<
2023-05-24 22:27:38,378 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:27:38,599 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:27:38,600 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:27:39,112 INFO root waitress-1 : Actual sign Dim=height=80 width=344
2023-05-24 22:27:39,114 INFO root waitress-1 : Required sign Dim=height=400 width=1000
2023-05-24 22:27:39,114 INFO root waitress-1 : _isblur1_=false isvalidface=true
2023-05-24 22:27:39,115 INFO root waitress-1 : >>----->>> END:UUID:=16b8bd7d-fa54-11ed-aabc-161333e62825 <<<-----<<
2023-05-24 22:27:55,189 INFO root waitress-2 : /validateImage....
2023-05-24 22:27:55,190 INFO root waitress-2 : >>----->>> START:UUID:=20be8566-fa54-11ed-b353-161333e62825 <<<-----<<
2023-05-24 22:27:55,193 INFO root waitress-2 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:27:55,414 INFO root waitress-2 : validate_input_file:isfile=True isurl=True
2023-05-24 22:27:55,415 INFO root waitress-2 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:27:55,647 DEBUG root waitress-2 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:27:55,872 ERROR app waitress-2 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 73, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:30:31,675 INFO root MainThread : Started
2023-05-24 22:30:31,692 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:30:32,935 INFO root waitress-0 : /validateImage....
2023-05-24 22:30:32,937 INFO root waitress-0 : >>----->>> START:UUID:=7ec4d743-fa54-11ed-86b4-161333e62825 <<<-----<<
2023-05-24 22:30:32,940 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:30:33,164 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:30:33,165 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:30:33,398 DEBUG root waitress-0 : Exception@get_image='str' object is not callable
2023-05-24 22:30:33,399 DEBUG root waitress-0 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:30:33,628 DEBUG root waitress-0 : Exception@get_image='str' object is not callable
2023-05-24 22:30:33,630 ERROR app waitress-0 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 74, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:30:38,513 INFO root waitress-1 : /validateImage....
2023-05-24 22:30:38,515 INFO root waitress-1 : >>----->>> START:UUID:=8217e077-fa54-11ed-ab4b-161333e62825 <<<-----<<
2023-05-24 22:30:38,517 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:30:38,716 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:30:38,717 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:30:38,953 DEBUG root waitress-1 : Exception@get_image='str' object is not callable
2023-05-24 22:30:38,955 DEBUG root waitress-1 : Xception@do_blur_detection='NoneType' object has no attribute 'shape'
2023-05-24 22:30:39,192 DEBUG root waitress-1 : Exception@get_image='str' object is not callable
2023-05-24 22:30:39,194 ERROR app waitress-1 : Exception on /validateImage [POST]
Traceback (most recent call last):
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 62, in process_image
    isvalidimage, remarks = validate_sign_params(image_file_path, isblur1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 143, in validate_sign_params
    sign_hi, sign_wi = get_resolution(image_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\commons.py", line 74, in get_resolution
    return (h, w)
            ^
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\balac\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\crossdomain.py", line 30, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\app.py", line 61, in validateImage
    data = process_image(image_file_path, img_type, app_id, id, uid, cur_datetime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\py-ValidateImageAPI\imageUtils.py", line 93, in process_image
    logging.debug("process_image:Exception="+e)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "UnboundLocalError") to str
2023-05-24 22:31:24,826 INFO root MainThread : Started
2023-05-24 22:31:24,843 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:31:28,376 INFO root waitress-0 : /validateImage....
2023-05-24 22:31:28,378 INFO root waitress-0 : >>----->>> START:UUID:=9fd06a55-fa54-11ed-b469-161333e62825 <<<-----<<
2023-05-24 22:31:28,379 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:31:28,591 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:31:28,591 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:31:28,838 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:31:29,054 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:31:29,363 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:31:29,573 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:31:29,627 INFO root waitress-0 : Actual sign Dim=height=153 width=96
2023-05-24 22:31:29,628 INFO root waitress-0 : Required sign Dim=height=400 width=1000
2023-05-24 22:31:29,629 INFO root waitress-0 : _isblur1_=false isvalidface=true
2023-05-24 22:31:29,630 INFO root waitress-0 : >>----->>> END:UUID:=9fd06a55-fa54-11ed-b469-161333e62825 <<<-----<<
2023-05-24 22:31:38,022 INFO root waitress-1 : /validateImage....
2023-05-24 22:31:38,023 INFO root waitress-1 : >>----->>> START:UUID:=a59024e4-fa54-11ed-b4f8-161333e62825 <<<-----<<
2023-05-24 22:31:38,024 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:31:38,248 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:31:38,248 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:31:38,725 INFO root waitress-1 : Actual sign Dim=height=80 width=344
2023-05-24 22:31:38,726 INFO root waitress-1 : Required sign Dim=height=400 width=1000
2023-05-24 22:31:38,728 INFO root waitress-1 : _isblur1_=false isvalidface=true
2023-05-24 22:31:38,729 INFO root waitress-1 : >>----->>> END:UUID:=a59024e4-fa54-11ed-b4f8-161333e62825 <<<-----<<
2023-05-24 22:32:12,173 INFO root waitress-2 : /validateImage....
2023-05-24 22:32:12,174 INFO root waitress-2 : >>----->>> START:UUID:=b9eb2f2d-fa54-11ed-ace8-161333e62825 <<<-----<<
2023-05-24 22:32:12,177 INFO root waitress-2 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:32:12,387 INFO root waitress-2 : validate_input_file:isfile=True isurl=True
2023-05-24 22:32:12,388 INFO root waitress-2 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:32:12,881 INFO root waitress-2 : Actual sign Dim=height=80 width=344
2023-05-24 22:32:12,882 INFO root waitress-2 : Required sign Dim=height=400 width=1000
2023-05-24 22:32:12,883 INFO root waitress-2 : _isblur1_=false isvalidface=true
2023-05-24 22:32:12,883 INFO root waitress-2 : >>----->>> END:UUID:=b9eb2f2d-fa54-11ed-ace8-161333e62825 <<<-----<<
2023-05-24 22:32:22,944 INFO root waitress-3 : /validateImage....
2023-05-24 22:32:22,945 INFO root waitress-3 : >>----->>> START:UUID:=c056a970-fa54-11ed-affe-161333e62825 <<<-----<<
2023-05-24 22:32:22,949 INFO root waitress-3 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=sign
2023-05-24 22:32:23,182 INFO root waitress-3 : validate_input_file:isfile=True isurl=True
2023-05-24 22:32:23,183 INFO root waitress-3 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:32:23,430 DEBUG urllib3.connectionpool waitress-3 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:32:23,636 DEBUG urllib3.connectionpool waitress-3 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:32:23,938 DEBUG urllib3.connectionpool waitress-3 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:32:24,163 DEBUG urllib3.connectionpool waitress-3 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:32:24,220 INFO root waitress-3 : Actual sign Dim=height=153 width=96
2023-05-24 22:32:24,221 INFO root waitress-3 : Required sign Dim=height=400 width=1000
2023-05-24 22:32:24,222 INFO root waitress-3 : _isblur1_=false isvalidface=true
2023-05-24 22:32:24,223 INFO root waitress-3 : >>----->>> END:UUID:=c056a970-fa54-11ed-affe-161333e62825 <<<-----<<
2023-05-24 22:32:31,672 INFO root waitress-0 : /validateImage....
2023-05-24 22:32:31,674 INFO root waitress-0 : >>----->>> START:UUID:=c58a8fa0-fa54-11ed-a40e-161333e62825 <<<-----<<
2023-05-24 22:32:31,675 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=face
2023-05-24 22:32:31,903 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:32:31,904 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:32:32,164 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:32:32,409 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:32:32,467 INFO root waitress-0 : is_face_valid:isurl=true
2023-05-24 22:32:32,472 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:32:32,674 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:32:32,766 INFO root waitress-0 : Face Locations=[(32, 78, 84, 26)]
2023-05-24 22:32:32,768 INFO root waitress-0 : is_face_valid=true
2023-05-24 22:32:33,022 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:32:33,250 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:32:33,352 INFO root waitress-0 : Actual face Dim=height=153 width=96
2023-05-24 22:32:33,353 INFO root waitress-0 : Required face Dim=height=1000 width=1000
2023-05-24 22:32:33,354 INFO root waitress-0 : _isblur1_=false isvalidface=true
2023-05-24 22:32:33,355 INFO root waitress-0 : >>----->>> END:UUID:=c58a8fa0-fa54-11ed-a40e-161333e62825 <<<-----<<
2023-05-24 22:32:47,970 INFO root waitress-1 : /validateImage....
2023-05-24 22:32:47,973 INFO root waitress-1 : >>----->>> START:UUID:=cf418e76-fa54-11ed-b82e-161333e62825 <<<-----<<
2023-05-24 22:32:47,975 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=face
2023-05-24 22:32:48,201 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:32:48,202 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:32:48,452 INFO root waitress-1 : is_face_valid:isurl=true
2023-05-24 22:32:48,457 DEBUG urllib3.connectionpool waitress-1 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:32:48,657 DEBUG urllib3.connectionpool waitress-1 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:32:48,730 INFO root waitress-1 : Face Locations=[]
2023-05-24 22:32:48,733 INFO root waitress-1 : is_face_valid=false
2023-05-24 22:32:48,965 INFO root waitress-1 : Actual face Dim=height=80 width=344
2023-05-24 22:32:48,968 INFO root waitress-1 : Required face Dim=height=1000 width=1000
2023-05-24 22:32:48,968 INFO root waitress-1 : _isblur1_=false isvalidface=false
2023-05-24 22:32:48,969 INFO root waitress-1 : >>----->>> END:UUID:=cf418e76-fa54-11ed-b82e-161333e62825 <<<-----<<
2023-05-24 22:33:27,069 INFO root waitress-2 : /validateImage....
2023-05-24 22:33:27,070 INFO root waitress-2 : >>----->>> START:UUID:=e68f6040-fa54-11ed-b5ff-161333e62825 <<<-----<<
2023-05-24 22:33:27,073 INFO root waitress-2 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:33:27,319 INFO root waitress-2 : validate_input_file:isfile=True isurl=True
2023-05-24 22:33:27,320 INFO root waitress-2 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:33:27,866 INFO root waitress-2 : Actual sign Dim=height=80 width=344
2023-05-24 22:33:27,868 INFO root waitress-2 : Required sign Dim=height=400 width=1000
2023-05-24 22:33:27,870 INFO root waitress-2 : _isblur1_=false isvalidface=true
2023-05-24 22:33:27,871 INFO root waitress-2 : >>----->>> END:UUID:=e68f6040-fa54-11ed-b5ff-161333e62825 <<<-----<<
2023-05-24 22:35:12,937 INFO root waitress-3 : /validateImage....
2023-05-24 22:35:12,939 INFO root waitress-3 : >>----->>> START:UUID:=25a9b3bc-fa55-11ed-aeb4-161333e62825 <<<-----<<
2023-05-24 22:35:12,940 INFO root waitress-3 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=face
2023-05-24 22:35:13,152 INFO root waitress-3 : validate_input_file:isfile=True isurl=True
2023-05-24 22:35:13,154 INFO root waitress-3 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:35:13,397 DEBUG urllib3.connectionpool waitress-3 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:35:13,594 DEBUG urllib3.connectionpool waitress-3 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:35:13,645 INFO root waitress-3 : is_face_valid:isurl=true
2023-05-24 22:35:13,648 DEBUG urllib3.connectionpool waitress-3 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:35:13,849 DEBUG urllib3.connectionpool waitress-3 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:35:13,912 INFO root waitress-3 : Face Locations=[(32, 78, 84, 26)]
2023-05-24 22:35:13,915 INFO root waitress-3 : is_face_valid=true
2023-05-24 22:35:14,155 DEBUG urllib3.connectionpool waitress-3 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:35:14,358 DEBUG urllib3.connectionpool waitress-3 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:35:14,410 INFO root waitress-3 : Actual face Dim=height=153 width=96
2023-05-24 22:35:14,411 INFO root waitress-3 : Required face Dim=height=1000 width=1000
2023-05-24 22:35:14,412 INFO root waitress-3 : _isblur1_=false isvalidface=true
2023-05-24 22:35:14,413 INFO root waitress-3 : >>----->>> END:UUID:=25a9b3bc-fa55-11ed-aeb4-161333e62825 <<<-----<<
2023-05-24 22:36:03,737 INFO root MainThread : Started
2023-05-24 22:36:03,753 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:36:04,876 INFO root waitress-0 : /validateImage....
2023-05-24 22:36:04,878 INFO root waitress-0 : >>----->>> START:UUID:=449ee255-fa55-11ed-bb9b-161333e62825 <<<-----<<
2023-05-24 22:36:04,880 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=face
2023-05-24 22:36:05,115 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:36:05,116 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:36:05,391 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:36:05,626 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:36:07,416 INFO root waitress-0 : is_face_valid:isurl=true
2023-05-24 22:36:07,421 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:36:07,633 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:36:07,694 INFO root waitress-0 : Face Locations=[(32, 78, 84, 26)]
2023-05-24 22:36:07,695 INFO root waitress-0 : is_face_valid=true
2023-05-24 22:36:07,961 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:36:08,193 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:36:09,028 INFO root waitress-0 : Actual face Dim=height=153 width=96
2023-05-24 22:36:09,031 INFO root waitress-0 : Required face Dim=height=1000 width=1000
2023-05-24 22:36:09,033 INFO root waitress-0 : _isblur1_=false isvalidface=true
2023-05-24 22:36:09,034 INFO root waitress-0 : >>----->>> END:UUID:=449ee255-fa55-11ed-bb9b-161333e62825 <<<-----<<
2023-05-24 22:36:15,929 INFO root waitress-1 : /validateImage....
2023-05-24 22:36:15,931 INFO root waitress-1 : >>----->>> START:UUID:=4b357813-fa55-11ed-aafe-161333e62825 <<<-----<<
2023-05-24 22:36:15,932 INFO root waitress-1 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/SIGN/SIGN_JPG62267/3113350824.jpg&filePath=basePath img_type=sign
2023-05-24 22:36:16,136 INFO root waitress-1 : validate_input_file:isfile=True isurl=True
2023-05-24 22:36:16,137 INFO root waitress-1 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:36:23,022 INFO root waitress-1 : Actual sign Dim=height=80 width=344
2023-05-24 22:36:23,024 INFO root waitress-1 : Required sign Dim=height=400 width=1000
2023-05-24 22:36:23,032 INFO root waitress-1 : _isblur1_=false isvalidface=true
2023-05-24 22:36:23,034 INFO root waitress-1 : >>----->>> END:UUID:=4b357813-fa55-11ed-aafe-161333e62825 <<<-----<<
2023-05-24 22:40:09,978 INFO root waitress-2 : /validateImage....
2023-05-24 22:40:09,979 INFO root waitress-2 : >>----->>> START:UUID:=d6b6571c-fa55-11ed-b96f-161333e62825 <<<-----<<
2023-05-24 22:40:09,981 INFO root waitress-2 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=face
2023-05-24 22:40:10,214 INFO root waitress-2 : validate_input_file:isfile=True isurl=True
2023-05-24 22:40:10,215 INFO root waitress-2 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:40:10,813 DEBUG urllib3.connectionpool waitress-2 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:40:11,021 DEBUG urllib3.connectionpool waitress-2 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:40:16,252 INFO root waitress-2 : is_face_valid:isurl=true
2023-05-24 22:40:16,256 DEBUG urllib3.connectionpool waitress-2 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:40:16,493 DEBUG urllib3.connectionpool waitress-2 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:40:16,562 INFO root waitress-2 : Face Locations=[(32, 78, 84, 26)]
2023-05-24 22:40:16,563 INFO root waitress-2 : is_face_valid=true
2023-05-24 22:40:16,792 DEBUG urllib3.connectionpool waitress-2 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:40:17,016 DEBUG urllib3.connectionpool waitress-2 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:40:19,160 INFO root waitress-2 : Actual face Dim=height=153 width=96
2023-05-24 22:40:19,163 INFO root waitress-2 : Required face Dim=height=1000 width=1000
2023-05-24 22:40:19,170 INFO root waitress-2 : _isblur1_=false isvalidface=true
2023-05-24 22:40:19,171 INFO root waitress-2 : >>----->>> END:UUID:=d6b6571c-fa55-11ed-b96f-161333e62825 <<<-----<<
2023-05-24 22:40:34,293 INFO root MainThread : Started
2023-05-24 22:40:34,310 INFO waitress MainThread : Serving on http://0.0.0.0:5001
2023-05-24 22:40:35,622 INFO root waitress-0 : /validateImage....
2023-05-24 22:40:35,624 INFO root waitress-0 : >>----->>> START:UUID:=e5ff6c8c-fa55-11ed-833b-161333e62825 <<<-----<<
2023-05-24 22:40:35,626 INFO root waitress-0 : process_image:image_file_path=https://tspsconetimereg.tspsc.gov.in/preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath img_type=face
2023-05-24 22:40:35,870 INFO root waitress-0 : validate_input_file:isfile=True isurl=True
2023-05-24 22:40:35,871 INFO root waitress-0 : validate_input_file2:isfile=True isurl=True
2023-05-24 22:40:36,127 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:40:36,332 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:40:36,402 INFO root waitress-0 : is_face_valid:isurl=true
2023-05-24 22:40:36,407 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:40:36,626 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:40:36,698 INFO root waitress-0 : Face Locations=[(32, 78, 84, 26)]
2023-05-24 22:40:36,700 INFO root waitress-0 : is_face_valid=true
2023-05-24 22:40:37,017 DEBUG urllib3.connectionpool waitress-0 : Starting new HTTPS connection (1): tspsconetimereg.tspsc.gov.in:443
2023-05-24 22:40:37,247 DEBUG urllib3.connectionpool waitress-0 : https://tspsconetimereg.tspsc.gov.in:443 "GET /preview.tspsc?fileName=Documents/JPG/PHOTO/PHOTO_JPG4/20467315081988.jpg&filePath=basePath HTTP/1.1" 200 None
2023-05-24 22:40:37,307 INFO root waitress-0 : Actual face Dim=height=153 width=96
2023-05-24 22:40:37,308 INFO root waitress-0 : Required face Dim=height=1000 width=1000
2023-05-24 22:40:37,309 INFO root waitress-0 : _isblur1_=false isvalidface=true
2023-05-24 22:40:37,311 INFO root waitress-0 : >>----->>> END:UUID:=e5ff6c8c-fa55-11ed-833b-161333e62825 <<<-----<<
